### ISSUE TITLE
Not able to signup with email at app.agentops.ai

### ISSUE THREAD

**Issue by vanetreg** [AgentOps-AI/agentops#557]
I try to signup at:
https://app.agentops.ai/signin (note endpoint ! )
with my email, but after entering username / pwd, it drops an error.

**Comment by NEWLEV** [comment]
Unable to login at all. Github allows me to set up, however, stuck on a blank canvas with options on the side. If you click an icon, it sends you back to https://app.agentops.ai/welcome

**Comment by areibman** [comment]
@NEWLEV Can you post a screenshot of what you mean? I think it's a related but separate issue from what OP has

**Comment by areibman** [comment]
> I try to signup at: https://app.agentops.ai/signin (note endpoint ! ) with my email, but after entering username / pwd, it drops an error.

Looks to be an issue with our auth flow. @ddtch @HowieG Let's investigate ASAP

**Comment by NEWLEV** [comment]
Good evening,I initially tried creating an account but it would continue to load as if I were signing in. I was able to login via github. Attached are the requested screenshots. Thanks!Regards,Pierre Montalvo
        
        
          On Dec 8 2024, at 6:15 pm, Alex Reibman ***@***.***> wrote:
          
        
        
           
@NEWLEV Can you post a screenshot of what you mean? I think it's a related but separate issue from what OP has

**Comment by areibman** [comment]
Hey @NEWLEV + @vanetreg we've fixed this error-- can you try again and let us know?

**Comment by ddtch** [comment]
I think this is solved. But would be nice ti check all emails like, restore password, magic link sign in etc

**Comment by NEWLEV** [comment]
Good afternoon,I'm still experiencing the same issue. Basically all links with exception to Docs - Report a Bug aren't responding. This includes Profile, billing, etc. However, Logout works. Once you try to log back in, you get the welcome screen and need to resubmit the "Before you get started" survey.Regards,Pierre Montalvo
        
        
          On Dec 10 2024, at 1:27 pm, David ***@***.***> wrote:
          
        
        
           
I think this is solved. But would be nice ti check all emails like, restore password, magic link sign in etc

**Comment by areibman** [comment]
> Good afternoon,I'm still experiencing the same issue. Basically all links with exception to Docs - Report a Bug aren't responding. This includes Profile, billing, etc. However, Logout works. Once you try to log back in, you get the welcome screen and need to resubmit the "Before you get started" survey.Regards,Pierre Montalvo On Dec 10 2024, at 1:27 pm, David ***@***.***> wrote: I think this is solved. But would be nice ti check all emails like, restore password, magic link sign in etc —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Hey @NEWLEV --I suspect you may have some sort of VPN or firewall causing this issue. Is that possibly the case?

Also we can help debug with you 1:1. Can you shoot me a private note to alex@agentops.ai ?

**Comment by ddtch** [comment]
@areibman @HowieG I made tiny pr that should fix problem with showing welcome page on pasword reset link. however I noticed that after resetting password I can't login with email. it always says wrong credentials. @HowieG please help me tmrw to debug this case

**Comment by areibman** [comment]
@vanetreg @NEWLEV Are you all still facing this issue?

**Comment by vanetreg** [comment]
> @vanetreg @NEWLEV Are you all still facing this issue?

I was able to signup and login with my email, although I miss some info after email confirmation ( if it was successful )
I close thread, thank you
